"""initial schema

Revision ID: aa2be2680e50
Revises: 
Create Date: 2026-08-10 11:09:25.588123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa2be2680e50'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('contacto', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('imei', sa.String(length=32), nullable=False),
    sa.Column('alias', sa.String(length=200), nullable=True),
    sa.Column('api_key', sa.String(length=64), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('imei')
    )
    op.create_index(op.f('ix_devices_tenant_id'), 'devices', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('numero_contenedor', sa.String(length=50), nullable=False),
    sa.Column('destino_pais', sa.String(length=100), nullable=False),
    sa.Column('mercado', sa.String(length=2), nullable=False),
    sa.Column('tipo_producto', sa.String(length=20), nullable=False),
    sa.Column('temp_min', sa.Float(), nullable=True),
    sa.Column('temp_max', sa.Float(), nullable=True),
    sa.Column('fecha_salida', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_llegada_estimada', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'numero_contenedor', name='uq_shipment_container_per_tenant')
    )
    op.create_index(op.f('ix_shipments_device_id'), 'shipments', ['device_id'], unique=False)
    op.create_index(op.f('ix_shipments_tenant_id'), 'shipments', ['tenant_id'], unique=False)
    op.create_table('certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('generado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hash_documento', sa.String(length=64), nullable=False),
    sa.Column('temp_min_registrada', sa.Float(), nullable=True),
    sa.Column('temp_max_registrada', sa.Float(), nullable=True),
    sa.Column('temp_promedio', sa.Float(), nullable=True),
    sa.Column('cantidad_alertas', sa.Integer(), nullable=False),
    sa.Column('cantidad_lecturas', sa.Integer(), nullable=False),
    sa.Column('url_pdf', sa.String(length=300), nullable=True),
    sa.Column('pdf_bytes', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificates_shipment_id'), 'certificates', ['shipment_id'], unique=False)
    op.create_table('readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperatura', sa.Float(), nullable=True),
    sa.Column('humedad', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('puerta_abierta', sa.Boolean(), nullable=False),
    sa.Column('vibracion', sa.Boolean(), nullable=False),
    sa.Column('tamper', sa.Boolean(), nullable=False),
    sa.Column('bateria', sa.Float(), nullable=True),
    sa.Column('fuente', sa.String(length=10), nullable=False),
    sa.Column('hash_actual', sa.String(length=64), nullable=False),
    sa.Column('hash_anterior', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_id', 'timestamp', name='uq_reading_shipment_timestamp')
    )
    op.create_index(op.f('ix_readings_shipment_id'), 'readings', ['shipment_id'], unique=False)
    op.create_index('ix_readings_shipment_time', 'readings', ['shipment_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_readings_timestamp'), 'readings', ['timestamp'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('reading_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('severidad', sa.String(length=10), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resuelta', sa.Boolean(), nullable=False),
    sa.Column('resuelto_por', sa.String(length=255), nullable=True),
    sa.Column('notificado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reading_id'], ['readings.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_resuelta'), 'alerts', ['resuelta'], unique=False)
    op.create_index(op.f('ix_alerts_shipment_id'), 'alerts', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_alerts_timestamp'), 'alerts', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_timestamp'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_shipment_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_resuelta'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_readings_timestamp'), table_name='readings')
    op.drop_index('ix_readings_shipment_time', table_name='readings')
    op.drop_index(op.f('ix_readings_shipment_id'), table_name='readings')
    op.drop_table('readings')
    op.drop_index(op.f('ix_certificates_shipment_id'), table_name='certificates')
    op.drop_table('certificates')
    op.drop_index(op.f('ix_shipments_tenant_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_device_id'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_devices_tenant_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_table('tenants')
    # ### end Alembic commands ###
